export { createAgentClient } from './client.js';
export type {
  AgentDynamicToolCallInput,
  AgentClient,
  AgentClientOptions,
  AgentDomainTool,
  AgentResolvedTool,
  AgentSessionCallback,
  AgentSessionClient,
  AgentSessionDomains,
  AgentSessionTools,
  AgentTapFilter,
  AgentTapStreamHandle,
  AgentTapStreamHandlers,
  AgentToolSchema,
  DomainDefinition,
} from './types.js';
export type {
  AgentErrorInfo,
  AgentResponseEnvelope,
  AgentServerInfo,
  AgentSessionInfo,
  AgentSessionStatus,
  AgentTool,
  AgentToolTraits,
  JSONSchema7,
  MetroTarget,
  SendAgentSessionTapMessageRequest,
  SendAgentSessionTapMessageResponse,
  TapDirection,
  TapEvent,
} from '@rozenite/agent-shared';
