packages:
  - packages/*
  - libs/*
  - apps/*
  - website

catalog:
  react: "19.2.0"
  react-dom: "19.2.0"
  "@types/react": "~19.2.2"
  "@types/react-dom": "~19.1.7"
  react-native: "0.83.1"
  vite: "^7.3.1"

onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@swc/core'
  - core-js
  - electron
  - esbuild
  - react-native-mmkv
  - react-native-nitro-modules
  - sqlite3